export const PREPARATION_GENERATION_SOURCES = Object.freeze([
  'TEMPLATE',
  'MANUAL',
  'PROVIDER',
  'NONE',
] as const)

export type PreparationGenerationSource =
  (typeof PREPARATION_GENERATION_SOURCES)[number]

export type PreparationAssetInputSource = 'MANUAL' | 'PROVIDER'
export type PreparationAssetStatus = 'PENDING' | 'AVAILABLE'

export interface PreparationAssetInput {
  readonly source: PreparationAssetInputSource
  readonly reference: string
}

export interface PreparationAssetSlot {
  readonly source: PreparationGenerationSource
  readonly reference: string | null
  readonly status: PreparationAssetStatus
}

export interface PreparationGeneratedText {
  readonly value: string
  readonly source: PreparationGenerationSource
}

export interface PreparationGenerationInput {
  readonly hostname: string
  readonly ownershipConfirmed: boolean
  readonly businessName?: string | null
  readonly category?: string | null
  readonly primaryKeyword?: string | null
  readonly city?: string | null
  /** Intended resale price, not acquisition cost or budget. */
  readonly askingPrice: number
  readonly currency: string
  /** Explicit external provider destination; never generated by this layer. */
  readonly externalSalesUrl: string
  readonly logo?: PreparationAssetInput | null
  readonly favicon?: PreparationAssetInput | null
  readonly openGraphImage?: PreparationAssetInput | null
}

export interface PreparationLandingPageConfiguration {
  readonly headline: PreparationGeneratedText
  readonly description: PreparationGeneratedText
  readonly askingPrice: number
  readonly currency: string
  readonly cta: Readonly<{
    label: PreparationGeneratedText
    externalSalesUrl: string
  }>
}

export interface PreparationSeoMetadata {
  readonly title: PreparationGeneratedText
  readonly description: PreparationGeneratedText
}

export interface PreparationOpenGraphMetadata {
  readonly title: PreparationGeneratedText
  readonly description: PreparationGeneratedText
  readonly image: PreparationAssetSlot
}

export interface PreparationGenerationResult {
  readonly hostname: string
  readonly description: PreparationGeneratedText
  readonly landingPage: PreparationLandingPageConfiguration
  readonly seo: PreparationSeoMetadata
  readonly openGraph: PreparationOpenGraphMetadata
  readonly assets: Readonly<{
    logo: PreparationAssetSlot
    favicon: PreparationAssetSlot
  }>
}

export interface PreparationGenerator {
  generate(
    input: PreparationGenerationInput
  ): PreparationGenerationResult | null | Promise<PreparationGenerationResult | null>
}

