CREATE TABLE `owned_domain_registrar_associations` (
  `id` varchar(36) NOT NULL,
  `account_id` varchar(36) NOT NULL,
  `owned_domain_id` varchar(36) NOT NULL,
  `provider_identifier` varchar(64) NOT NULL,
  `provider_domain_identifier` varchar(255) NULL,
  `registrar_status` enum('ACTIVE','INACTIVE','EXPIRED','TRANSFER_AWAY','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  `expires_at` datetime(3) NULL,
  `auto_renew` boolean NULL,
  `first_seen_at` timestamp(3) NOT NULL,
  `last_seen_at` timestamp(3) NOT NULL,
  `last_synced_at` timestamp(3) NOT NULL,
  `sync_state` enum('SEEN','MISSING') NOT NULL DEFAULT 'SEEN',
  `provenance_reference` varchar(255) NOT NULL,
  `version` int unsigned NOT NULL DEFAULT 1,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT `registrar_assoc_pk` PRIMARY KEY (`id`),
  CONSTRAINT `registrar_assoc_account_fk` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `registrar_assoc_owned_domain_account_fk` FOREIGN KEY (`owned_domain_id`, `account_id`) REFERENCES `owned_domains` (`id`, `account_id`) ON DELETE CASCADE,
  CONSTRAINT `registrar_assoc_domain_provider_uq` UNIQUE (`owned_domain_id`, `provider_identifier`),
  CONSTRAINT `registrar_assoc_version_ck` CHECK (`version` >= 1),
  INDEX `registrar_assoc_account_provider_state_idx` (`account_id`, `provider_identifier`, `sync_state`),
  INDEX `registrar_assoc_account_domain_idx` (`account_id`, `owned_domain_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
